//add your allowlists here. They need to be in the same format as you used to generate your merkle root.
//You can also add them here and copy the route from the console log
export const allowLists = new Map<string, Array<string>>([
  [
    "cbarF",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
      "AG8FoBErQ7WGKKJQBfomVdVxuhTRJPKT9C8sAYK2BUcV",
      "5HA4hfPTZD1cAJPqUNUMpgnP9zzP5uiEPo6VyS4nV7QB",
    ],
  ],
  [
    "cbarP",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
      "AG8FoBErQ7WGKKJQBfomVdVxuhTRJPKT9C8sAYK2BUcV",
      "5HA4hfPTZD1cAJPqUNUMpgnP9zzP5uiEPo6VyS4nV7QB",
    ],
  ],
  [
    "wlGF",
    [
      "4Wq25E4eMqFe4g95qf6P1E6XyHvk2L4UJn32S39mPfc4",
    ],
  ],
  [
    "wlGP",
    [
      "4Wq25E4eMqFe4g95qf6P1E6XyHvk2L4UJn32S39mPfc4",
    ],
  ],
  [
    "wlFCFS",
    [
      "Dtf28H8rgDzj26XxPyexpoMa5ccKnKSp5rVRmjPX9RpL",
      "6afNZ1CHhMnG1UVAnKmQMSUXdBndduSAc81ysY3Bfeob",
    ],
  ],
]);
