//add your allowlists here. They need to be in the same format as you used to generate your merkle root.
//You can also add them here and copy the route from the console log
export const allowLists = new Map<string, Array<string>>([
  [
    "cbarF",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
    ],
  ],
  [
    "cbarP",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
    ],
  ],
  [
    "wlGF",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
    ],
  ],
  [
    "wlGP",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
    ],
  ],
  [
    "wlFCFS",
    [
      "2ZekZevhKVu7fVntaeraRmJK9xrgkDQfch8PF1FgY62E",
      "FJx3g6nV6t5Tgo9KbGjuVARt6QKwauyDLVrktmjdQRJk",
      "42uZwJcKDeqGjLgxB2fhsP5VtubpQak5GJXkXsHYW8o8",
    ],
  ],
  [
    "default",
    [
      "Tes1zkZkXhgTaMFqVgbgvMsVkRJpq4Y6g54SbDBeKVV",
      "GjwcWFQYzemBtpUoN5fMAP2FZviTtMRWCmrppGuTthJS",
      "AT8nPwujHAD14cLojTcB1qdBzA1VXnT6LVGuUd6Y73Cy",
    ],
  ],
]);
